server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RatingServiceDB
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:8085
#  application:
#    name: RATING-SERVICE

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#     defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

